#!/bin/bash
echo "=== BUSINESS MATCH SEBRAE - CHECKLIST DEPLOY ==="
echo ""
echo "✅ 1. Teste Gunicorn Local:"
echo "   gunicorn --bind 0.0.0.0:5001 wsgi:app --timeout 120 --workers 1"
echo ""
echo "✅ 2. Configurações Render:"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: gunicorn wsgi:app --timeout 120 --workers 2"
echo ""
echo "✅ 3. Variáveis de Ambiente:"
echo "   FLASK_ENV=production"
echo "   SECRET_KEY=(gerar chave forte)"
echo "   DATABASE_URL=(provisionado automaticamente)"
echo ""
echo "✅ 4. Database Setup:"
echo "   No Render: Acessar Console → flask db upgrade"
echo ""
echo "✅ 5. Testes Pós-Deploy:"
echo "   - Login com usuários teste"
echo "   - Sistema de swipe"
echo "   - Matches e WhatsApp"
echo ""
echo "=== PRONTO PARA DEPLOY! ==="
