services:
  - type: web
    name: business-match-mvp
    env: node
    rootDir: services/mvp-node
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
