services:
- type: web
  name: business-match
  env: python
  plan: starter
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn "app:create_app()" -c gunicorn.conf.py
  envVars:
  - key: SECRET_KEY
    generateValue: true
  - key: DATABASE_URL
    sync: false
  - key: FLASK_ENV
    value: production
  healthCheckPath: /
